# Minimal mapping of common US large-caps you’ll actually see in headlines.
UNIVERSE = {
    "APPLE": "AAPL",
    "MICROSOFT": "MSFT",
    "ALPHABET": "GOOGL",
    "GOOGLE": "GOOGL",
    "AMAZON": "AMZN",
    "NVIDIA": "NVDA",
    "META": "META",
    "TESLA": "TSLA",
    "NETFLIX": "NFLX",
    "ADOBE": "ADBE",
    "ORACLE": "ORCL",
    "INTEL": "INTC",
    "ADVANCED MICRO DEVICES": "AMD",
    "AMD": "AMD",
    "BROADCOM": "AVGO",
    "SALESFORCE": "CRM",
    "PAYPAL": "PYPL",
    "SHOPIFY": "SHOP",
    "COSTCO": "COST",
    "WALMART": "WMT",
    "DISNEY": "DIS",
    "COCA-COLA": "KO",
    "PEPSICO": "PEP",
    "JPMORGAN": "JPM",
    "BANK OF AMERICA": "BAC",
    "VISA": "V",
    "MASTERCARD": "MA",
    "UNITEDHEALTH": "UNH",
    "ELI LILLY": "LLY",
    "PFIZER": "PFE",
    "MODERNA": "MRNA",
    "EXXON": "XOM",
    "CHEVRON": "CVX",
}
